---

# UNCOMMENT THIS
# - name: read admin pwd
#   shell: cat /var/lib/jenkins/secrets/initialAdminPassword
#   register: adminpwd

- name: Install python-jenkins library
  pip:
    name: python-jenkins
    state: present
 
- name: Create SSH credentails
  become: true
  jenkins_script:
    script: "{{ lookup('file', 'templates/credential.groovy') }}"
    user: admin
    password: "{{ administrator_pass }}"
# "{{adminpwd.stdout}}" 
- name: Create Jenkins pipeline job
  jenkins_script:
    user: admin
    password: "{{ administrator_pass }}"
    # "{{ adminpwd.stdout }}"
    url: "http://{{public_ip_address}}"
    script: "{{ lookup('file', 'templates/test2.groovy') }}"
