---
- name : Enble or SELinux
  hosts: nehra
  vars:
    status: disabled
    tasks:
    - name: change SELinux un cinfuguration file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX={{status}}'https://docs.google.com/presentation/d/1fdl6uCl9btF1sjSSmczFW06WJCUz6LmEYjh0ipxie1I/edit?usp=sharing