---
# tasks file for ssh-up
- name: Wait for SSH to come up
  wait_for:
    host: "{{ public_ip_address }}"
    port: 22
    delay: 10
    timeout: 120
    state: started
  with_items: "{{ ec2.instances }}"