---
# tasks file for configure-master

- name: Task to create security gruoup # 1 - Create my security group
  local_action: 
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group for webserver Servers
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Task to launch ec2 instance # 2 Launch the new EC2 Instance
  ec2_instance:
    security_group: "{{ security_group }}" 
    instance_type: "{{ instance_type}}"
    image_id: "{{ image }}" 
    wait: true 
    region: "{{ region }}" 
    tags:
      Name: "{{ instance_name }}"
    key_name: "{{ keypair }}"  
    state: started
    instance_role: "{{ iam_instance_profile }}"
  register: ec2

- debug:
    var: ec2

- set_fact:
    public_ip_address: "{{ec2.instances[0].public_ip_address}}"
    private_ip_address: "{{ec2.instances[0].private_ip_address}}"
    # instance_id: "{{ec2_instance.instance_ids}}"


- name: Configure node file with IP address
  ansible.builtin.replace:
    path: /home/yohenba.kshetrimayum/ansible/node
    regexp: 'example.com'
    replace: '{{public_ip_address}}'

- name: Print IP address
  debug:
    var: "{{public_ip_address}}"